=== Pepitusmaxi/New/futbol.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Jugadores_champions">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="jugador" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>	
							<xs:element name="posicion" type="xs:integer"/>
							<xs:element name="equipos" type="xs:string"/>
							<xs:element name="Goles" type="xs:integer"/>
							<xs:element name="Partidos" type="xs:integer"/>
							<xs:element name="GolesporPartido" type="xs:decimal"/>
						</xs:sequence>
						<xs:attribute name="nombre" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Pepitusmaxi/New/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Jugadores_champions
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="futbol.xsd">
		<jugador nombre="Erling Braut HÃ¥land">
				<posicion>1</posicion>
				<equipos>Borussia Dormunt</equipos>
				<Goles>10</Goles>
				<Partidos>8</Partidos>
				<GolesporPartido>1.25</GolesporPartido>
		</jugador>
		<jugador nombre="MbappÃ©">
				<posicion>2</posicion>
				<equipos>Paris Saint Germain</equipos>
				<Goles>8</Goles>
				<Partidos>9</Partidos>
				<GolesporPartido>0.89</GolesporPartido>
		</jugador>
		<jugador nombre="Rashford">
				<posicion>3</posicion>
				<equipos>Manchester United</equipos>
				<Goles>6</Goles>
				<Partidos>6</Partidos>
				<GolesporPartido>1</GolesporPartido>
		</jugador>
		<jugador nombre="Giroud">
				<posicion>4</posicion>
				<equipos>Chelsea</equipos>
				<Goles>6</Goles>
				<Partidos>7</Partidos>
				<GolesporPartido>0.86</GolesporPartido>
		</jugador>
		<jugador nombre="Neymar">
				<posicion>5</posicion>
				<equipos>Paris Saint Germain</equipos>
				<Goles>6</Goles>
				<Partidos>7</Partidos>
				<GolesporPartido>0.86</GolesporPartido>
		</jugador>
</Jugadores_champions>
